In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
iris = load_iris(as_frame= True)
list(iris)

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [3]:
iris.data.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [4]:
iris.target.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
pd.DataFrame(iris.target).value_counts()

target
0         50
1         50
2         50
Name: count, dtype: int64

In [7]:
X = iris.data
y = iris.target

In [8]:
X.corrwith(y)

sepal length (cm)    0.782561
sepal width (cm)    -0.426658
petal length (cm)    0.949035
petal width (cm)     0.956547
dtype: float64

In [9]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42, stratify= y)

In [ ]:
log_reg = LogisticRegression(C= 30, random_state= 42)
log_reg.fit(x_train, y_train)

log_reg.score(x_train, y_train)

0.9833333333333333

In [12]:
predict = log_reg.predict(x_test)

print(log_reg.score(x_test, y_test))

1.0


In [13]:
test = [ i == j for i,j in zip(y_test, predict)]

pd.DataFrame(test).value_counts()

0   
True    30
Name: count, dtype: int64

In [14]:
print(accuracy_score(y_test, predict))          # 0.9667
print(confusion_matrix(y_test, predict))        # shows WHICH class got confused

1.0
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [ ]:
# using Probability

predict = log_reg.predict_proba(x_test)

print(log_reg.score(x_test, y_test))